reload the ***** thing

diff --git a/src/Synology/scripts/postinst b/src/Synology/scripts/postinst
--- a/src/Synology/scripts/postinst
+++ b/src/Synology/scripts/postinst
@@ -1,4 +1,6 @@
-#!/bin/sh
+!/bin/sh 
+#
+# postinst:
 #
 # WebTools - Initial download and firewall configuration settings installation for Synology
 #
@@ -6,136 +8,266 @@
 # by ChuckPa, a Plex Community member
 #
 # Ver 1.0 - Initial release
+# Ver 1.1 - Processor independence update ('noarch')
+# Ver 1.2 - DSM 5.2 & 6.0 (U3) single version compatibility (Syno installer changes) + Upgrade-in-place
+#           Split Log (install) and Upgrade history log
 
 
 # Put error messages in appropriate system log / communicate back to user
+WriteSyno() {
 
+  if [ "$SYNOPKG_TEMP_LOGFILE" == "" ]; then
+    return 0
+  fi
+
+  touch  "$SYNOPKG_TEMP_LOGFILE"
+  echo `date +"%Y-%m-%e %H.%M.%S %Z"`: $* >> "$SYNOPKG_TEMP_LOGFILE"
+} 
+
+# Writes permanent history (log) to WebTools.bundle/WebTools.log
 WriteLog() {
-
-    touch       "$LOGFILE"
-    echo `date -Iseconds` $*  >> "$LOGFILE"
-#	/sbin/log_tool -t 0 -a "$*"
-
+  
+  # Also inform user via Syno package mechanism if it is active, else it's our logfile
+  touch   "$LOGFILE"
+  echo `date +"%Y-%m-%e %H.%M.%S %Z"`: $* >> "$LOGFILE"
+    
 }
-
+    
+#================================================================
 GetHostType() {
  
-# define the main flags
+  # define the main flags
+ 
+  # Location of the needed executables if not in standard locations
+  CURL=/usr/bin/curl
+  TAR=/bin/tar
+  UNZIP=/usr/syno/bin/unzip
+  
+  # where the package is located
+  PKGDIR=/var/packages/WebTools
 
-HOSTYPE=0
-
-    HOSTTYPE=2   # SYNO
-    CURL=/usr/bin/curl
-    TAR=/bin/tar
-    UNZIP=/usr/syno/bin/unzip
-    PKGDIR=/var/packages/WebTools
-
-  return 0
-
+ return 0
+   
 }
-
+   
 GetDestination() {
-
-    # On Synology,  the Pre-install script will have been run to determine if Plex is
-    # installed.  It will error if not.
-
-    PMS_DIR="`synoshare --get Plex | grep Path | awk -F\[ '{ print $2 }' \
-                                                   | awk -F\] '{ print $1 }'`"
-
-    WEBTOOLS_DIR="$PKGDIR/target"
-
+   
+  # On Synology,  the Pre-install script determines if Plex is present and ok to use ($PMS_DIR)
+   
+  PMS_DIR="`synoshare --get Plex | grep Path | awk -F\[ '{ print $2 }' \
+  | awk -F\] '{ print $1 }'`"
+  
   # Now build the Plug-in directory
-
   PLUGIN_DIR="$PMS_DIR/Library/Application Support/Plex Media Server/Plug-ins"
-
-  # The Logfile (just in case)
+  
+  # Our default Logfile
   LOGFILE="$PLUGIN_DIR/WebTools.log"
-
+  
   # Which release.   Release info for WebTools on Github
   RELEASE_LINK="https://api.github.com/repos/dagalufh/WebTools.bundle/releases/latest" 
-
-}
-
+  
+  }
+  
 ######################################################################
 # Get latest release download link, and download that
 ######################################################################
 downloadWT(){
-	# Let's start by finding the browser_download_url
-	# we will use the tarball directly for now.  (keep both here)
-
-        # That again means, that QNAP'ers using this is not counted :-(
-#	DownloadURL=$(/sbin/curl -Lsk $RELEASE_LINK |grep 'browser_download_url')
-#       DownloadURL=$(/sbin/curl -Lsk $RELEASE_LINK |grep 'tarball_url')
-	DownloadURL="`$CURL -Lsk $RELEASE_LINK |grep 'tarball_url'`"
-
-	# Strip start part of line
-	DownloadURL="`echo $DownloadURL | sed -e 's/"tarball_url": "//'`"
-
-	
-        # Strip end part of the response
-        DownloadURL="`echo $DownloadURL | sed -e 's/..$//'`"
-
-
-        WriteLog "Webtools completing download and installation" 
-
-#echo DownloadURL = \[$DownloadURL\]
-
-	# Download the darn thingy
-	$CURL -Lsk $DownloadURL -o "$PLUGIN_DIR/wt.tar.gz"
-	if [ $? -ne 0 ]; then
-          WriteLog Error $? while downloading WebTools
-          return $? 
-        fi
-
-        #WriteLog WebTools download complete
-
+  
+  # Let's start by finding the browser_download_url
+  # we will use the tarball directly for now.  (keep both here)
+      
+  # That again means, that QNAP'ers using this is not counted :-(
+  #  DownloadURL=$(/sbin/curl -Lsk $RELEASE_LINK |grep 'browser_download_url')
+  #   DownloadURL=$(/sbin/curl -Lsk $RELEASE_LINK |grep 'tarball_url')
+  DownloadURL="`$CURL -Lsk $RELEASE_LINK |grep 'tarball_url'`"
+      
+  # Strip start part of line
+  DownloadURL="`echo $DownloadURL | sed -e 's/"tarball_url": "//'`"
+    
+      
+  # Strip end part of the response
+  DownloadURL="`echo $DownloadURL | sed -e 's/..$//'`"
+    
+    
+  WriteLog "Updating from $DownloadURL" 
+    
+    
+  # Download the darn thingy
+  $CURL -Lsk $DownloadURL -o "$PLUGIN_DIR/wt.tar.gz"
+  if [ $? -ne 0 ]; then
+    WriteLog Error $? while downloading WebTools
+    WriteSyno ERROR $? while downloading WebTools
+    return $? 
+  fi
+        
+  return 0
 }
-
+      
 ######################################################################
 # Create WT dir if missing, and then extract. remove tarball afterwards
 ######################################################################
 extractWT(){
-
-#echo extractWT: mkdir $PLUGIN_DIR/WebTools.bundle >>  $LOGFILE
-
-	mkdir -p "$PLUGIN_DIR/WebTools.bundle"
-        $TAR -xf "$PLUGIN_DIR/wt.tar.gz" --overwrite --strip 1 -C "$PLUGIN_DIR/WebTools.bundle"
-
-        rm -f "$PLUGIN_DIR/wt.tar.gz"
-#	$UNZIP -oq "$PLUGIN_DIR/wt.zip" -d "$PLUGIN_DIR/WebTools.bundle"
-
-
-        # On Synology,  set ownership to plex, not root.
-        chown -R plex:users "$PLUGIN_DIR/WebTools.bundle"
-        find "$PLUGIN_DIR" -type f -exec chmod 644 {} \;
-        find "$PLUGIN_DIR" -type d -exec chmod 755 {} \;
-
+      
+  if [ $ISUPGRADE ]; then
         
+    WriteLog  "Forcing upgrade with installer upgrade"
+        
+  else
+      
+echo about to create WebTools.bundle dir
+  # Create WebTools.bundle directory
+    mkdir -p "$PLUGIN_DIR/WebTools.bundle"
+    #WriteLog extractWT: mkdir $PLUGIN_DIR/WebTools.bundle
+      
+    if [ $? -ne 0 ]; then
+      MSG="ERROR: Could not create WebTools.bundle directory in \' $PLUGIN_DIR '\  \(err $? \) "
+      WriteLog $MSG
+      WriteSyno $MSG
+      return 1
+    fi
+  fi
+        
+  # Extract WebTools
+  $TAR -xf "$PLUGIN_DIR/wt.tar.gz" --overwrite --strip 1 -C "$PLUGIN_DIR/WebTools.bundle"
+  if [ $? -ne 0 ]; then
+      # unable to extract
+      MSG="ERROR:  Cannot extract wt.tar.gz to $PLUGIN_DIR/WebTools.bundle \(err $?\)"
+      WriteSyno "$MSG"
+      WriteLog  "$MSG"
+      return 1
+  fi
+        
+  rm -f "$PLUGIN_DIR/wt.tar.gz"
+  #    $UNZIP -oq "$PLUGIN_DIR/wt.zip" -d "$PLUGIN_DIR/WebTools.bundle"
+      
+      
+  # On Synology,  set ownership to plex, not root.
+  chown -R plex:users "$PLUGIN_DIR/WebTools.bundle"
+  find "$PLUGIN_DIR/WebTools.bundle" -type f -exec chmod 644 {} \;
+  find "$PLUGIN_DIR/WebTools.bundle" -type d -exec chmod 755 {} \;
+      
+  # Success
+  return 0
+      
 }
-
+      
 #######################################################################
-
+      
 # Get the host type and Destination directories then download and install WebTools into Plex
-
+      
 GetHostType
 GetDestination
+      
 
-# Download and extract
-downloadWT
-extractWT
+# Initialize
+IsUpgrade=0
+Retries=0
+Downloaded=0
+PlexRunning=0
 
-# Mark as loaded
-touch "$PLUGIN_DIR/WebTools.bundle/.isloaded"
-
-# Make certain the files in /var/packages are owned by root 
-chown -R root:root   /var/packages/WebTools
-
-
-# Add description of firewall ports to DSM's firewall built-in application list
-/usr/syno/bin/servicetool --install-configure-file --package /var/packages/WebTools/target/WebTools.sc
-if [ $? -eq 0 ]; then
-  WriteLog WebTools firewalls rules definition installed
+# Determine if Install or Upgrade
+if [ -f "/usr/local/webtools_upgrade" ]; then
+  IsUpgrade=1
+  WriteLog "Previous version detected.  Upgrade/Overwrite forced."
 fi
 
+# Determine if Plex is running or not
+if [ -f "$PMS_DIR/Library/Application Support/Plex Media Server/plexmediaserver.pid" ]; then
+  PlexRunning=1
+fi        
 
+# If Plex running and this is an upgrade,  stop Plex
+if [ $IsUpgrade -eq 1 -a $Plexrunning -eq 1 ]; then
+  /usr/syno/bin/synopkg stop "Plex Media Server"
+fi;
+        
+until [ $Retries -gt 5 -o $Downloaded -eq 1 ]; do
+        
+  # Try the download 
+  downloadWT
+  
+  # Check the return
+  if [ $? -ne 0 ]; then
+    retries=`expr $retries + 1`
+    WriteLog "ERROR: Cannot download WT from GitHub, sleeping 10 sec. Retry \# $retries"
+    sleep 10
+        
+  else
+    Downloaded=1
+    break
+      
+  fi
+        
+done
+        
+# Write results in logfile, exit if unable to proceed
+if [ $Downloaded -eq 1 ]; then
+  
+  # Downloaded is true (no error)  Log it
+  WriteLog  "Download successful.  Proceeding with installation."
+  WriteSyno "WebTools download successful.  Proceeding with installation."
+  
+else
+
+  MSG="ERROR: Unable to download WebTools after $retries retries.  Installation failure."
+  WriteSyno "$MSG"
+  WriteLog  "$MSG"
+
+  # If Plex was running, restart it
+  if [$IsUpgrade -eq 1 -a $PlexRunning -eq 1 ]; then
+    /usr/syno/bin/synopkg start "Plex Media Server"
+  fi
+
+  exit 1
+
+fi
+        
+        
+        
+# If download was successful,  perform extraction
+extractWT  
+if [ $? -ne 0 ]; then
+        
+# unable to extract WT and complete installation... ERROR
+  MSG="ERROR: Could not extract WebTools.  Package installation aborted."
+  WriteSyno "$MSG"
+  WriteLog "$MSG"
+
+  # If Plex was running, restart it
+  if [$IsUpgrade -eq 1 -a $PlexRunning -eq 1 ]; then
+    /usr/syno/bin/synopkg start "Plex Media Server"
+  fi
+
+  exit 1
+fi
+      
+      
+# Mark as loaded
+  touch "$PLUGIN_DIR/WebTools.bundle/.isloaded"
+      
+  # Make certain the files in /var/packages are owned by root 
+  chown -R root:root   /var/packages/WebTools
+      
+      
+  # If upgrade, force remove firewall descriptions before upgrading (should already be gone)
+  if [ $ISUPGRADE ]; then
+    WriteLog Removing previous firewall definitions
+    /usr/syno/bin/servicetool --remove-configure-file --package WebTools.sc
+  fi
+      
+  # Add description of firewall ports to DSM's firewall built-in application list
+  /usr/syno/bin/servicetool --install-configure-file --package /var/packages/WebTools/target/WebTools.sc
+      
+  if [ $? -eq 0 ]; then
+    WriteLog New firewall rules definition installed
+  fi
+
+  # If an upgrade,  restart Plex
+  if [$IsUpgrade -eq 1 -a $PlexRunning -eq 1 ]; then
+    /usr/syno/bin/synopkg start "Plex Media Server"
+  fi
+        
+  WriteLog  WebTools installation complete.
+  WriteLog  " "
+        
 exit 0
diff --git a/src/Synology/scripts/preuninst b/src/Synology/scripts/preuninst
--- a/src/Synology/scripts/preuninst
+++ b/src/Synology/scripts/preuninst
@@ -1,34 +1,51 @@
 #!/bin/sh
 #
-# Uninstall WebTools from DSM
+# (Pre) Uninstall WebTools from DSM
 #
 # by ChuckPa, a Plex Community member
 #
 # Ver 1.0 - Initial release
+# Ver 1.1 - Make DSM platform independent.  Rely on Plex dependence only
+# Ver 1.2 - Update to accomodate DSM 6.0 U3 installer changes
+#           Remove Firewall definitions from list but do not remove from firewall
+#                  to avoid corruption of Firewall database
+# Ver 1.3 - Changed 'uninstall' to be complete "Synology-style" uninstall...  'ALL GONE'
 
 
-# If there is no Plex, there's nothing to do
+# If there is no Plex, skip over the Plex stuff
 synoshare --get Plex
-if [ $? -ne 0 ]
-then
-   exit 0
-fi
+if [ $? -ne 0 ]; then
 
-# Ok, so Plex is still there,  Where is it and let's do our cleanup
-PLEX_LIBRARY_PATH="`synoshare --get Plex | grep Path | \
+  # Ok, so Plex is still there,  Where is it and let's do our cleanup
+  PLEX_LIBRARY_PATH="`synoshare --get Plex | grep Path | \
                            awk -F\[ '{ print $2 }' | awk -F\] '{ print $1 }'`"
 
-# remove WebTools from the Plug-ins Dir
+  # remove WebTools from the Plug-ins Dir (Complete Synology-style uninstall)
+  rm -rf "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle"
 
-## From PR 3-Apr-2016,  Leave Firewall description intact since WebTools.bundle stays
-#rm -rf "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle"
+  # Remove the cache directory
+  rm -rf "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-in Support/CCaches/com.plexapp.plugins.WebTools"
 
-# Remove the ".isrunning" flag (Synology has no further hooks into Webtools)
-rm -f "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/.isrunning"
+  # Remove the Data directory
+  rm -rf "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.WebTools"
 
-# remove the Synology GUI integration link (This is required to avoid a mess)
-rm -f /usr/syno/synoman/webman/3rdparty/WebTools
+  # remove the Synology GUI integration link (This is required to avoid a mess)
+  rm -f /usr/syno/synoman/webman/3rdparty/WebTools
 
+  LOG="$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.log"
 
-# Remove the built-in firewall settings
-/usr/syno/bin/servicetool --remove-configure-file --package /var/packages/WebTools/target/WebTools.sc
+fi
+
+# Remove the built-in firewall settings (DSM 5 and 6)
+/usr/syno/bin/servicetool --remove-configure-file --package WebTools.sc
+/usr/syno/bin/servicetool --remove-configure-file --build-in WebTools.sc
+/usr/syno/bin/servicetool --remove-configure-file --package WebTools
+/usr/syno/bin/servicetool --remove-configure-file --build-in WebTools
+
+# Log the removal if Plex present
+if [ -d "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins" ]; then
+  echo `date +"%Y-%m-%e %H.%M.%S %Z"`: WebTools uninstalled >> "$LOG"
+fi
+
+exit 0
+
